### ISSUE TITLE
IE11 Object doesn't support property or method '_fromString'

### ISSUE THREAD

**Issue by yavorski** [lifaon74/url-polyfill#31]
Hi, after update to `1.1.0`, we are getting this error in `IE11`:

```
Object doesn't support property or method '_fromString'
```

in this peace of code:

```
this.searchParams._fromString(this.search);
```

Previous version of the polyfill worked fine.

I have no idea why this happens...

Also it would be nice to separate `URL` and `URLSearchParams` polyfills so we could use only one of them, and replace the other one with something else in cases like this.

Best regards!

**Comment by lifaon74** [comment]
Should be fixed. It seems you're polyfilling URLSearchParams from another piece of code, else this would't append. All tests are passing.
Both URL and URLSearchParams  are closely correlated and cannot be (and shouldn't) be separate.

**Comment by lifaon74** [comment]
Wow, hopefully you noticed it, I forgot to publish the last version. Could you please check than the 1.1.1 is now working ? Thanks for your help.

**Comment by treyhoover** [comment]
Ah, just tested 1.1.1 on Safari 10.0. Unfortunately there's still an error but the error is different with this release:

![screen shot 2018-11-27 at 10 10 59 am](https://user-images.githubusercontent.com/10567194/49090994-eb99ad00-f22c-11e8-896b-35d316491739.png)

Let me know if there's anything else I can do to help.

**Comment by lifaon74** [comment]
Ok I commit a version that should work on safari. Could you test it lpease(1.1.2) ?
